config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  root to: 'home#index'

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :items do
      collection do
        delete '/images/:id', to: 'items#delete_attached_image', as: :delete_attached_image
      end
    end

    resources :categories
    resources :orders
  end
  resources :search

  resources :items, only: :index

  namespace :cart do
    resources :cart_items, only: [:create, :destroy, :update, :index] do
      collection do
        delete 'destroy_all'
      end
    end

    get '/checkout', to: 'cart_items#checkout'
  end

  resources :orders, only: [:index, :create]
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :items, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/controllers/cart/cart_items_controller.rb
class Cart::CartItemsController < ApplicationController
  before_action :authenticate_user!, only: :checkout

  def index
    @cart_items = current_cart.cart_items
  end

  def create
    @cart_item = current_cart.cart_items.build(item_id: params[:item_id])
    
    if @cart_item.save
      flash[:success] = 'Item successfully added to your cart'
      redirect_to cart_cart_items_path
    else
      flash[:alert] = 'Something went wrong'
      redirect_back(fallback_location: root_path)
    end
  end

  def update
    @cart_item = CartItem.find_by(id: params[:id])

    respond_to do |format|
      unless @cart_item.update(cart_item_params)
        format.js do
          set_flash_message('could not update cart item')
        end
      else
        format.js
      end
    end
  end

  def destroy
    cart_item = CartItem.find_by(id: params[:id])
    cart_item.delete if cart_item
    redirect_back(fallback_location: root_path)
  end

  def destroy_all
    current_cart.cart_items.destroy_all
    redirect_back(fallback_location: root_path)
  end

  def checkout; end

  private

  def cart_item_params
    params.require(:cart_item).permit(:quantity)
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def create
    @cart_item = CartItem.new(
      cart_id: @cart.id,
      item_id: params[:item_id]
    )

    respond_to do |format|
      if @cart_item.save
        format.js do
          set_flash_message('Item added to cart')
        end
      else
        format.js do
          set_flash_message('something went wrong')
        end
      end
    end
  end

  def destroy_all
    @cart.cart_items.destroy_all
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/carts/cart_items_controller.rb
class Carts::CartItemsController < ApplicationController
  def index
    @cart_items = @cart.cart_items
  end

  def create
    @cart_item = @cart.cart_items.build(item_id: params[:item_id])
    
    respond_to do |format|
      if @cart_item.save
        format.js do
          set_flash_message('Item added to cart')
        end
      else
        format.js do
          set_flash_message('something went wrong')
        end
      end
    end
  end

  def destroy_all
    @cart.cart_items.destroy_all
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show; end
end

app/views/cart/cart_items/checkout.html.haml
%h1 Checkout

= "items ( #{current_cart.cart_items.sum(:quantity)} ) => AU $#{current_cart.items.sum("cart_items.quantity * items.price")}"

%br
%br

%b= "Total => AU $#{current_cart.items.sum("cart_items.quantity * items.price")}" 
  
%br
%br
%br

= button_to 'Confirm and Pay', orders_path

app/views/cart/cart_items/create.js.erb
$('h3#cart_icon span').text(<%= current_cart.items.count %>)

app/views/cart/cart_items/index.html.haml
%h2 Your Cart Items

- @cart_items.each do |cart_item|
  %b= cart_item.item.title
  = form_with model: [:cart, cart_item], html: {style: "display: inline"}  do |f|
    = f.select(:quantity, [1,2,3,4,5], {}, onchange: 'Rails.fire(this.form, "submit")')
  = link_to 'Remove Item', cart_cart_item_path(cart_item), method: :delete
  %hr

%div{style: "padding-top: 10px;"}
  = link_to 'Clear cart', destroy_all_cart_cart_items_path, method: :delete

%div{style: "padding-top: 10px;"}
  = button_to 'Checkout', cart_checkout_path, method: :get

app/views/cart/cart_items/update.js.erb
$('h3#cart_icon span').text(<%= current_cart.items.sum(:quantity) %>)