config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  root to: 'home#index'

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :items do
      collection do
        delete '/images/:id', to: 'items#delete_attached_image', as: :delete_attached_image
      end
    end

    resources :categories
    resources :orders
  end
  resources :search

  resources :items, only: :index

  namespace :cart do
    resources :cart_items, only: [:create, :destroy, :update, :index] do
      collection do
        delete 'destroy_all'
      end
    end

    get '/checkout', to: 'cart_items#checkout'
  end

  resources :orders, only: [:index, :create]
end

app/models/order.rb
class Order < ApplicationRecord

  enum status: {
    ordered: "ordered",
    paid: "paid",
    cancelled: "cancelled",
    completed: "completed"
  }

  has_many :order_items
  has_many :items, through: :order_items

  belongs_to :user

  def self.find_by_status(status)
    if statuses.keys.include?(status)
      where(status: status)
    else
      all
    end
  end

  def subtotal
    items.pluck(:price, :id).inject(0) do |subtotal, item|
      subtotal + (item[0] * OrderItem.quantity_for(id, item[1]))
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::ApplicationController
  before_action :set_order, only: [:show, :update]

  def index
    @orders = Order.find_by_status(params[:status])
  end

  def show; end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.js do
          set_flash_message('Order updated successfully')
        end
      else
        format.js do
          set_flash_message("Error!")
        end
      end
    end
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(
      :status
    )
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = current_user.orders
  end

  def create
    # Make Payment
    # if payment success
    order = current_user.orders.build(status: 'paid')

    current_cart.cart_items.each do |cart_item|
      order.order_items.build(
        item_id: cart_item.item_id,
        quantity: cart_item.quantity
      )
    end

    if order.save
      flash[:success] = 'order placed successfully'
      session.delete(:cart_id)
      redirect_to root_path
    else
      flash[:alert] = "Order could not be placed"
    end
  end
end

app/views/admin/orders/_order.html.haml
%tr{id:"#{order.id}"}
  %td= order.id
  %td.status= order.status
  %td.action
    - if order.ordered? || order.paid?
      = link_to "cancel", admin_order_path(order, order:{status:'cancelled'}), remote: true, method: :put, class: 'cancel'

    - if order.ordered?
      = link_to "mark as paid", admin_order_path(order, order:{status:'paid'}), remote: true, method: :put, class: 'paid'

    - if order.paid?
      = link_to "mark as completed", admin_order_path(order, order:{status:'completed'}), remote: true, method: :put, class: 'completed'

    = link_to "show", admin_order_path(order), class: 'show'

app/views/admin/orders/index.html.haml
%h1 All Orders

= form_with(url: admin_orders_path, method: :get, local: true) do
  = select_tag(:status, options_for_select(Order.statuses.to_a, selected: params[:status]), prompt: 'All')

  = submit_tag "Search", name: nil

%table{width: "100%"}
  %tr
    %th Order ID
    %th Status
    %th Link
  = render @orders

app/views/admin/orders/show.html.haml
%h1= "Order_#{@order.id}"

%p 
  %b Ordered date: 
  #{@order.created_at}

%p
  %b Status: 
  #{@order.status}

app/views/admin/orders/update.js.erb
(function() {

  let $linkCompleted = $('<a>')
  $linkCompleted.attr("href", "<%=admin_order_path(@order, order:{status:'completed'})%>")
  $linkCompleted.attr("data-remote", 'true')
  $linkCompleted.text('mark as completed')
  $linkCompleted.attr("data-method", "put")
  $linkCompleted.attr("rel", "nofollow")
  $linkCompleted.addClass("completed")

  const order_status = '<%=@order.status%>'
  const $order_tr = $('tr#<%= @order.id %>')

  $order_tr.find('.status').text(order_status)

  const hidePaidLink = () => {
    const $paidlLink = $order_tr.find('.action a.paid')
    $paidlLink.removeAttr('href');
    $paidlLink.hide();
  }

  const hideCancelLink = () => {
    const $cancelLink = $order_tr.find('.action a.cancel')
    $cancelLink.removeAttr('href');
    $cancelLink.hide();
  }

  const insertCompletedLink = () => {
    const $paidLink = $order_tr.find('.action .paid')
    $linkCompleted.insertBefore($paidLink)
  }

  const hideCompletedLink = () => {
    const $linkCompleted = $order_tr.find('.action a.completed')
    $linkCompleted.removeAttr('href');
    $linkCompleted.hide();
  }

  if(order_status == 'paid') {
    hidePaidLink()
    insertCompletedLink()
  } 

  if(order_status == 'cancelled') {
    hideCancelLink()
    hidePaidLink()
  }

  if(order_status == 'completed') {
    hideCancelLink()
    hideCompletedLink()
  }

})();