config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins

  root to: 'home#index'

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :items do
      collection do
        delete '/images/:id', to: 'items#delete_attached_image', as: :delete_attached_image
      end
    end

    resources :categories
    resources :orders
  end
  resources :search

  resources :items, only: :index

  namespace :cart do
    resources :cart_items, only: [:create, :destroy, :update, :index] do
      collection do
        delete 'destroy_all'
      end
    end

    get '/checkout', to: 'cart_items#checkout'
  end

  resources :orders, only: [:index, :create]
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :items, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :item_categories
  has_many :items, through: :item_categories

  validates_presence_of :name
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :item_categories
  has_many :categories, through: :item_categories
  has_many_attached :images

  validates :categories, presence: true
  validates_presence_of :title, :desc
  validates_uniqueness_of :title
  validates_numericality_of :price, greater_than: 0
end

app/models/item_category.rb
class ItemCategory < ApplicationRecord
  belongs_to :item
  belongs_to :category
end

app/models/order.rb
class Order < ApplicationRecord

  enum status: {
    ordered: "ordered",
    paid: "paid",
    cancelled: "cancelled",
    completed: "completed"
  }

  has_many :order_items
  has_many :items, through: :order_items

  belongs_to :user

  def self.find_by_status(status)
    if statuses.keys.include?(status)
      where(status: status)
    else
      all
    end
  end

  def subtotal
    items.pluck(:price, :id).inject(0) do |subtotal, item|
      subtotal + (item[0] * OrderItem.quantity_for(id, item[1]))
    end
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def self.quantity_for(order_id, item_id)
    where(order_id: order_id, item_id: item_id).
      pluck(:quantity).
      first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.js do
          flash[:notice] = 'Item saved'
          redirect_to admin_item_path @item
        end
      else
        format.js do
          set_flash_message(@item.errors.full_messages)
        end
      end
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.images.attach(item_params[:images]) if item_params[:images].present?

    respond_to do |format|
      if @item.update(item_params.except(:images))
        format.js do
          set_flash_message('Item updated successfully')
          redirect_to admin_items_path
        end
      else
        format.js do
          set_flash_message("Error! Please fill the form properly")
        end
      end
    end
  end

  def delete_attached_image
    @image = ActiveStorage::Attachment.find(params[:id]) 
    @image.purge
    redirect_back(fallback_location: edit_admin_item_path)  
  end

  private

  def item_params
    params.require(:item).permit(
      :title, 
      :desc, 
      :price,
      :active_for_sale,
      category_ids: [],
      images: []
    )
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::ApplicationController
  before_action :set_order, only: [:show, :update]

  def index
    @orders = Order.find_by_status(params[:status])
  end

  def show; end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.js do
          set_flash_message('Order updated successfully')
        end
      else
        format.js do
          set_flash_message("Error!")
        end
      end
    end
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(
      :status
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CartSessionHelper

  before_action :current_cart

  def set_flash_message(msg)
    response.set_header('Flash-Message',msg ) 
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def create
    @cart_item = CartItem.new(
      cart_id: @cart.id,
      item_id: params[:item_id]
    )

    respond_to do |format|
      if @cart_item.save
        format.js do
          set_flash_message('Item added to cart')
        end
      else
        format.js do
          set_flash_message('something went wrong')
        end
      end
    end
  end

  def destroy_all
    @cart.cart_items.destroy_all
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show; end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @items = Item.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = current_user.orders
  end

  def create
    # Make Payment
    # if payment success
    order = current_user.orders.build(status: 'paid')

    current_cart.cart_items.each do |cart_item|
      order.order_items.build(
        item_id: cart_item.item_id,
        quantity: cart_item.quantity
      )
    end

    if order.save
      flash[:success] = 'order placed successfully'
      session.delete(:cart_id)
      redirect_to root_path
    else
      flash[:alert] = "Order could not be placed"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_session_helper.rb
module CartSessionHelper
  def current_cart
    @current_cart ||= Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    cart = Cart.create
    session[:cart_id] = cart.id
  end
end

app/views/admin/shared/_header.html.haml
.header
  %h1#logo 
    = link_to 'Dinner Dash', root_path

  %nav
    %ul
      - if admin_signed_in?
        %li= link_to 'Sign out', destroy_admin_session_path, method: :delete

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DinnerDash
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/messages'
    = render 'admin/shared/header'
    = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DinnerDash
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/messages'
    = render 'shared/header'
    = render 'shared/cart' unless controller.controller_name == "carts"
    = yield

app/views/shared/_cart.html.haml
%h3#cart_icon 
  = link_to cart_cart_items_path do
    Shopping Cart Items (
    %span= current_cart.items.sum(:quantity)
    )

app/views/shared/_header.html.haml
.header
  %h1#logo 
    = link_to 'Dinner Dash', root_path

  %nav#top_nav
    %ul
      - if user_signed_in?
        %li= link_to 'Sign out', destroy_user_session_path, method: :delete
        %li= link_to 'My orders', orders_path
      - else
        %li= link_to 'Sign up', new_user_registration_path
        %li= link_to 'Sign in', new_user_session_path

app/views/shared/_messages.html.haml
.row
  .column
    - flash.each do |name, msg|
      %div
        %i
        = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)